public enum BS_TfliteMessageType : byte
{
    GetTfliteName,
    SetTfliteName,
    GetTfliteTask,
    SetTfliteTask,
    GetTfliteSensorRate,
    SetTfliteSensorRate,
    GetTfliteSensorTypes,
    SetTfliteSensorTypes,
    IsTfliteReady,
    GetTfliteCaptureDelay,
    SetTfliteCaptureDelay,
    GetTfliteThreshold,
    SetTfliteThreshold,
    GetTfliteInferencingEnabled,
    SetTfliteInferencingEnabled,
    TfliteInference
}